FROM python:3.10-slim

RUN apt-get update && \
    apt-get install --yes --no-install-recommends curl git wget jq

# /// TESTING \\\
ENV KWOK_REPO=kubernetes-sigs/kwok
ENV KWOK_LATEST_RELEASE=v0.7.0
ENV KWOK_OS=linux
# ENV KWOK_ARCH=arm64

RUN wget -O kwokctl -c "https://github.com/${KWOK_REPO}/releases/download/${KWOK_LATEST_RELEASE}/kwokctl-${KWOK_OS}-$(dpkg --print-architecture)" \
    && chmod +x kwokctl \
    && mv kwokctl /usr/local/bin/kwokctl

RUN wget -O kwok -c "https://github.com/${KWOK_REPO}/releases/download/${KWOK_LATEST_RELEASE}/kwok-${KWOK_OS}-$(dpkg --print-architecture)" \
    && chmod +x kwok \
    && mv kwok /usr/local/bin/kwok

ENV KUBECTL_VERSION=v1.33.5
RUN curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/${KWOK_OS}/$(dpkg --print-architecture)/kubectl" \
    && chmod +x kubectl \
    && mv kubectl /usr/local/bin/kubectl

# /// SWEEPER \\\
WORKDIR /app
COPY requirements.txt .

RUN pip install --upgrade pip wheel setuptools && \
    pip install --no-cache-dir -r requirements.txt

COPY . /app/

RUN pip install --no-cache-dir . && sweeper --version

ENV HOME="/home/sweeper"
RUN groupadd -r -g 3001 sweeper && useradd -r -d $HOME -u 3001 -g sweeper sweeper
RUN mkdir -p $HOME
RUN chown sweeper $HOME
USER sweeper

ENTRYPOINT [ "sh", "/app/test/kwok/kwok.sh" ]
