name: test gha

on:
  workflow_dispatch:

jobs:
  test-gha:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Get application version
        run: echo "version=$(python3 setup.py --version)" >> $GITHUB_ENV

      - name: Short Sha
        run: echo "shortsha=$(git rev-parse --short=7 ${{ github.sha }})" >> $GITHUB_ENV

      - name: run cmds
        run: pwd && ls -lah
